// Artifact store (local) v0.1

use std::path::Path;
use chrono::Utc;

pub fn save_artifact(path: &Path) {
    // Minimal artifact index/metadata for v0.1
    let meta = serde_json::json!({
        "timestamp": Utc::now().to_rfc3339(),
        "note": "artifact bundle generated by awen-runtime v0.1",
    });
    let _ = std::fs::write(path.join("metadata.json"), serde_json::to_string_pretty(&meta).unwrap());

    // TODO: create SQLite index and support S3-compatible storage
}
